accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views
from .forms import LoginForm

urlpatterns = [
    path('login/', LoginView.as_view(
        form_class=LoginForm,
        template_name='accounts/login_form.html'
    ), name='login'),
    # LogoutView.as_view(next_page='') 리졸브 url을 사용하기 때문에 다음 페이지를 지정해줄 수 있지만
    # https://github.com/django/django/blob/main/django/contrib/auth/views.py
    # global setting에 주소를 세팅해주는 게 더 낫다
    # https://github.com/django/django/blob/main/django/conf/global_settings.py
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('signup/', views.signup, name='signup'),
]

instagram/urls.py
from django.urls import path, re_path, register_converter
from . import views, converter
from .converter import MonthConverter, YearConverter, DayConverter

register_converter(MonthConverter, 'month')
register_converter(YearConverter, 'year')
register_converter(DayConverter, 'day')


app_name = 'instagram' # URL Reverse에서 namespace 역할


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),
    # path('archive/2020/', views.archives_year),
    # path('archive/<int:year>/', views.archives_year),
    # re_path(r'archive/(?P<year>20\d{2})', views.archives_year),
    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year>/<month:month>', views.post_archive_month, name='post_archive_month'),
    # path('archive/<year>/<month:month>/<day:day>', views.post_archive_day, name='post_archive_day'),
]

kingcompany/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django.conf import global_settings + from kingcompany import settings
from django.conf import settings
from django.views.generic import TemplateView, RedirectView


urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),
    # path('', RedirectView.as_view(url='/instagram'), name='root'),
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('instagram/', include('instagram.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),
    ]

instagram/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator
# from django.contrib.auth.models import User

# min_length_Validator = MinLengthValidator(3)
# min_length_Validator("he") # forms.ValidationError


class Post(models.Model):
    #   auth.User            장고에서 사용하는 가장 좋은 방법
    # models.GenericIPAddressField   조회수 컨트롤의 용이할듯
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='1')
    message = models.TextField(
        validators=[MinLengthValidator(5)]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y%m')
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # return f"Custom Post object ({self.id})"
        return self.message

    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

    class Meta:
        ordering = ['-id']


class Comment(models.Model):
    # limit_choices_to = {'is_public': True})
    post = models.ForeignKey('instagram.Post', on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

instagram/forms.py
import re
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'message', 'photo', 'is_public'
        ]
    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message:
            message = re.sub(r'[a-zA-z]+', '', message)
        return message

instagram/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, CreateView, UpdateView, \
    DeleteView
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from requests import post
from .models import Post
from .forms import PostForm
from django.contrib import messages


# @login_required
# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             messages.success(request, '포스팅을 저장했습니다')
#             return redirect(post)
#     else:
#         form = PostForm()
#
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': None,
#     })

#로그인 리콰이어드 사용해도 되고, 인자에 로그인 리과이어드 믹스인을 사용하면 된다
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request, '포스팅을 저장했습니다')
        return super().form_valid(form)


post_new = PostCreateView.as_view()


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.reqeust, '포스팅을 수정했습니다')
        return super().form_valid(form)

post_edit = PostUpdateView.as_view()

# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     # 장식자로 만들어서 추가하자
#     if post.author != request.user:
#         from django.contrib import messages
#         messages.error(request, '작성자만 추가할 수 있습니다')
#         return redirect(post)
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             # messages.success(request, '포스팅을 수정했습니다')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#
#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': post,
#     })

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    # success_url = '/instagram/'
    # success_url = reverse('instagram:post_list')
    # 리버스가 안되는 이유:
    # 파이썬은 소스가 임포트될 때 한줄 한줄 시작된다. 리버스(석세스 url)은 소스코드가 읽혀질 때 실행된다.
    # 즉 장고 초기화, 프로젝트를 로딩하기 전에 실행된다.
    # 이를 해결하기 위해 메서드로 만들어서 사용할 때 호출해도 되고,
    # def get_success_url(self):
    #     return reverse('instagram:post_list')
    success_url = reverse_lazy('instagram:post_list')
    # 해도 된다


post_delete = PostDeleteView.as_view()


# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request, '성공적인 삭제')
#         return redirect('instagram:post_list')
#     return render(request, 'instagram/post_confirm_delete.html', {
#       'post': post,
#     })


# post_list = login_required(ListView.as_view(model=Post, paginate_by=10))
@method_decorator(login_required, name='dispatch')
class PostListView(ListView):
    model = Post
    paginate_by = 100


post_list = PostListView.as_view()


# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#     if q:
#         qs = qs.filter(message__icontains=q)
#
#     # instagram/templates/instagram/post_list.html
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q': q,
#     })


# def post_detail(request: HttpRequest, pk) -> HttpRequest:
#     post = get_object_or_404(Post, pk=pk)
#
#     # try:
#     #     Post.objects.get(pk=pk)
#     # except Post.DoesNotExist:
#     #     raise Http404
#
#     return render(request, 'instagram/post_detail.html', {'post': post, })
#     return response

# post_detail = DetailView.as_view(
#     model=Post,
#     queryset=Post.objects.filter(is_public=True)
#     )


class PostDetailView(DetailView):
    model = Post
    # queryset = Post.objects.filter(is_public=True)

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=False)
        return qs


post_detail = PostDetailView.as_view()


# def archives_year(request, year):
#     return HttpResponse(f"{year}년 archives")

post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=10)

post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at', make_object_list=True)

instagram/templates/instagram/layout.html
{% extends "layout.html" %}

instagram/templates/instagram/post_archive.html
<h2>Latest</h2>

{{ latest }}

<h2>Date List</h2>

{% for date in date_list %}
{{ date.year }}
{% endfor %}

instagram/templates/instagram/post_archive_year.html
{{ year }}
{{ previous_year }}
{{ next_year }}
{{ date_list }}
{{ object_list }}

instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
<form action="" method="post">
{% csrf_token %}
<div class="alert alert-danger">
    정말 삭제하시겠습니까?
</div>

    <input type="submit" value="삭제하겠습니다." class="btn btn-danger" />
    <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
        아니요
    </a>
</form>
{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}
Post Detail
{% block title %}
Instagram / Post List
{% endblock title %}
{% block content %}
<h2>Author: {{ post.author }}</h2>

{% if post.photo %}
<div>
    <img src="{{ post.photo.url }}"/>
</div>
{% endif %}

{{ post.message|linebreaks }}

<!-- linebreaks, linbreaksbr -->
<hr/>
<div class="d-flex align-items-center">
    <a href="{% url 'instagram:post_list' %}" class="btn btn-dark " style="font-size: 40px">
        목록
    </a>
    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-light" style="font-size: 40px">
        수정
    </a>
    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger" style="font-size: 40px">
        삭제
    </a>
</div>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}


    <!--    <table>-->
    <!--        {{ form }}-->
    <!--    </table>-->
    {% buttons %}
    <button type="submit" class="btn btn-dark">저장
    </button>
    {% endbuttons %}
</form>
<hr/>
{% if post %}
<a href="{{ form.instance.get_absolute_url }}" class="btn btn-secondary">
    내용으로
</a>
{% endif %}

<a href="{% url 'instagram:post_list' %}" class="btn btn-info>목록</a>

{% endblock content %}

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}
Instagram / Post List
{% block title %}
Instagram / Post List
{% endblock title %}
{% block content %}
<form action="" method="get">
    <input type="type" name="q" value="{{q}}"/>
    <input type="submit" value="검색"/>
</form>

<a href="{% url 'instagram:post_new' %}" class="btn btn-dark col-12 mt-2 mb-2">새 포스트</a>

<table class="table table-bordered ">
    <tbody>
    {% for post in post_list %}
    <tr>
        <td>
            {{ post.pk }}
        </td>
        <td>

            {% if post.photo %}
            <img src="{{ post.photo.url }}" style="width: 100px;"/>
            {% else %}
            No Photo
            {% endif %}
        </td>
        <td>
            <a href="{{ post.get_absolute_url }}">
                {{ post.message }}
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{% if is_paginated %}
{% bootstrap_pagination page_obj size="large" justify_content="center" %}
{% endif %}


{% endblock content %}